import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Manual sidebar for the ROS 2 module
  ros2Sidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/introduction',
        {
          type: 'category',
          label: 'Chapter 1: Introduction to ROS 2',
          items: [
            'module-1-ros2/chapter-1-introduction-to-ros2/index',
            'module-1-ros2/chapter-1-introduction-to-ros2/what-is-ros2',
            'module-1-ros2/chapter-1-introduction-to-ros2/ros2-vs-ros1',
            'module-1-ros2/chapter-1-introduction-to-ros2/installation-setup',
            'module-1-ros2/chapter-1-introduction-to-ros2/ros2-ecosystem-tools',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: ROS 2 Fundamentals',
          items: [
            'module-1-ros2/chapter-2-ros2-fundamentals/intro',
            'module-1-ros2/chapter-2-ros2-fundamentals/nodes-and-lifecycle',
            'module-1-ros2/chapter-2-ros2-fundamentals/topics-and-messaging',
            'module-1-ros2/chapter-2-ros2-fundamentals/services-and-actions',
            'module-1-ros2/chapter-2-ros2-fundamentals/parameters-and-launch',
            'module-1-ros2/chapter-2-ros2-fundamentals/summary',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Python AI to ROS Integration',
          items: [
            'module-1-ros2/chapter-3-python-ai-ros-integration/index',
            'module-1-ros2/chapter-3-python-ai-ros-integration/python-ros-client-libraries',
            'module-1-ros2/chapter-3-python-ai-ros-integration/ai-model-integration',
            'module-1-ros2/chapter-3-python-ai-ros-integration/computer-vision-integration',
            'module-1-ros2/chapter-3-python-ai-ros-integration/ml-pipelines',
            'module-1-ros2/chapter-3-python-ai-ros-integration/ai-ros-communication-patterns',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 4: URDF for Humanoid Robots',
          items: [
            'module-1-ros2/chapter-4-urdf-humanoid-robots/index',
            'module-1-ros2/chapter-4-urdf-humanoid-robots/urdf-fundamentals',
            'module-1-ros2/chapter-4-urdf-humanoid-robots/humanoid-kinematics',
            'module-1-ros2/chapter-4-urdf-humanoid-robots/advanced-urdf-features',
            'module-1-ros2/chapter-4-urdf-humanoid-robots/urdf-control-integration',
            'module-1-ros2/chapter-4-urdf-humanoid-robots/humanoid-specific-design',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
